version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    networks: 
      - twitteranalysesnetwork
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  cassandra:
    image: cassandra:3
    hostname: cassandra
    networks: 
      - twitteranalysesnetwork
    ports:
      - "9042:9042"
    volumes: 
      - ./data/cassandra:/var/lib/cassandra
    restart: always  

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    hostname: broker-1
    ports:
      - "9092:9092"
    networks: 
      - twitteranalysesnetwork
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: '192.168.1.106'
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: 'Tweets'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    restart: always
  
  sparkmaster:
    image: bde2020/spark-master:2.3.1-hadoop2.7
    hostname: sparkmaster
    container_name: sparkmaster
    environment:
      INIT_DAEMON_STEP: setup_spark
      SPARK_CONF_DIR: /conf
    networks: 
      - twitteranalysesnetwork
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
    restart: always

  sparkworker:
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    hostname: sparkworker
    container_name: sparkworker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_MASTER: spark://sparkmaster:7077
    networks: 
      - twitteranalysesnetwork
    ports:
      - "8081"
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
    depends_on: 
      - sparkmaster
    restart: always
  
  sparktwitterapp:
    image: spark-streaming-kafka-cassandra
    hostname: sparktwitterapp
    container_name: sparktwitterapp
    environment: 
      SPARK_MASTER_NAME: sparkmaster
      SPARK_MASTER_PORT: 7077
    networks: 
      - twitteranalysesnetwork
    depends_on: 
      - sparkmaster
    restart: always

networks:
    twitteranalysesnetwork: