version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0-beta30-1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  cassandra:
    image: cassandra:3
    hostname: cassandra
    ports:
      - "9042:9042"  

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.0.0-beta30-1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ""
      KAFKA_CREATE_TOPICS: "tweets"
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    restart: always
  
  sparkmaster:
    image: gettyimages/spark:2.3.0-hadoop-3.0
    command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip master
    hostname: master
    environment:
      SPARK_CONF_DIR: /conf
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data

  sparkworker:
    image: gettyimages/spark:2.3.0-hadoop-3.0
    command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - kafka
      - sparkmaster
      - cassandra
    ports:
      - "8081"
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data